In [1]:
import numpy as np

In [2]:
empty_array = np.empty((3, 3))
print(empty_array)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 8.597e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


In [3]:
full_array = np.full((2, 2), 7)
print(full_array)

[[7 7]
 [7 7]]


In [4]:
zeros_array = np.zeros((3, 4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
ones_array = np.ones((2, 3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])
combined_array = np.vstack((arr1, arr2))
print(combined_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
array = np.array([[0, 5, 0], [8, 0, 0]])
non_zero_count = np.count_nonzero(array)
print(non_zero_count)

2
