In [1]:
import numpy as np

In [2]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
max_value = np.max(matrix)
print(max_value)

45


In [3]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
min_value = np.min(matrix)
print(min_value)

5


In [4]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
rows, columns = matrix.shape
print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 3
Number of columns: 3


In [5]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
addition_result = np.add(matrix1, matrix2)
subtraction_result = np.subtract(matrix1, matrix2)
print("Addition:")
print(addition_result)
print("Subtraction:")
print(subtraction_result)

Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]


In [7]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
multiplication_result = np.matmul(matrix1, matrix2)
print(multiplication_result)

[[19 22]
 [43 50]]


In [8]:
matrix = np.array([[1, 2], [3, 4]])
row_to_add = np.array([[5, 6]])
updated_matrix = np.vstack((matrix, row_to_add))
print(updated_matrix)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
matrix = np.array([[1, 2], [3, 4]])
column_to_add = np.array([[5], [6]])
updated_matrix = np.hstack((matrix, column_to_add))
print(updated_matrix)

[[1 2 5]
 [3 4 6]]


In [11]:
matrix = np.array([[1, 2], [3, 4]])
eigenvalues = np.linalg.eigvals(matrix)
print(eigenvalues)

[-0.37228132  5.37228132]


In [12]:
array = np.array([1, 2, 3, 1, 2, 2, 4, 5, 4, 3, 3])
unique_values, value_counts = np.unique(array, return_counts=True)
frequencies = np.asarray((unique_values, value_counts)).T
print(frequencies)

[[1 2]
 [2 3]
 [3 3]
 [4 2]
 [5 1]]


In [13]:
matrix = np.array([[1, 2], [3, 4]])
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
matrix = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(matrix)
print(determinant)

-2.0000000000000004


In [15]:
covariance_matrix = np.array([[1.0, 2.0], [2.0, 5.0]])
correlation_matrix = np.corrcoef(covariance_matrix)
print(correlation_matrix)

[[1. 1.]
 [1. 1.]]
