In [1]:
import numpy as np

In [2]:
# Create a NumPy array with random values
arr = np.random.rand(3, 3)
print("1. NumPy array with random values:\n", arr)

1. NumPy array with random values:
 [[0.8582281  0.64105384 0.17235415]
 [0.12677486 0.24241833 0.5780214 ]
 [0.7001582  0.53824382 0.93894647]]


In [3]:
# Generate random numbers from the uniform distribution using NumPy
uniform_random_numbers = np.random.uniform(low=0.0, high=1.0, size=5)
print("2. Random numbers from the uniform distribution:\n", uniform_random_numbers)

2. Random numbers from the uniform distribution:
 [0.17804659 0.59284009 0.37895654 0.6864004  0.47672106]


In [4]:
# Return a matrix of random values from a uniform distribution
uniform_matrix = np.random.uniform(low=0.0, high=1.0, size=(3, 3))
print("3. Matrix of random values from a uniform distribution:\n", uniform_matrix)

3. Matrix of random values from a uniform distribution:
 [[0.6738529  0.42335504 0.94448457]
 [0.56190658 0.09631283 0.01006094]
 [0.91188912 0.44327796 0.13953032]]


In [5]:
# Return a matrix of random values from a Gaussian distribution
gaussian_matrix = np.random.normal(loc=0.0, scale=1.0, size=(3, 3))
print("4. Matrix of random values from a Gaussian distribution:\n", gaussian_matrix)

4. Matrix of random values from a Gaussian distribution:
 [[ 0.40558687 -0.94634232  1.06251343]
 [ 0.10846687 -0.40812295 -1.52657631]
 [ 0.99606603  0.68519474 -0.19232914]]
